### PR TITLE
facebook and google oauth added

### PR DESCRIPTION
**Pull request by RunTerror**
`Implemented OAuth Functionality in GraphQL Resolvers and Type Definitions`

Implemented OAuth functionality by creating resolvers and type definitions. Additionally, granted appropriate permissions to the OAuth resolver in the index.js file.

This pull request addresses issue #138

### CODE REVIEW

**Comment by RunTerror** [comment]
@cfsmp3 @aadibajpai, kindly review my pull request and provide any feedback or suggested changes.

**Comment by Akshatji800** [comment]
Looks good to me

**Comment by RunTerror** [comment]
@aadibajpai please review this pr

**Comment by Akshatji800** [comment]
@RunTerror resolve the ci failing issues please

**Pull request closed without merging**
