### PR TITLE
fix leader name is being returned as anon.

### PR DESCRIPTION
**Pull request by Aadeesh11**
fixes: #75, https://github.com/CCExtractor/beacon/issues/35

### CODE REVIEW

**Comment by Aadeesh11** [comment]
@aadibajpai i have tested this change locally as well.

**Comment by Aadeesh11** [comment]
Can we merge this @aadibajpai , or something else also needs to be done?

**Comment by aadibajpai** [comment]
looks good provided this is what's needed, note that every populate call makes things slightly slower in general but it should not be too bad.

**Comment by Aadeesh11** [comment]
Sure, i understand populates makes it a little bit slower but in the end we need leader information (in frontend).

**Comment by Aadeesh11** [comment]
@aadibajpai when would the changes be reflected at the graphQl playground/ deployed to cloud?

**Pull request merged**
