### PR TITLE
feat: Deactivate beacon mutation.

### PR DESCRIPTION
**Pull request by Aadeesh11**
fixes: #78

### CODE REVIEW

**Comment by Aadeesh11** [comment]
@aadibajpai i have tested this locally, and its working as expected.

**Comment by aadibajpai** [comment]
why can't we just use the duration changing mutation?

**Comment by Aadeesh11** [comment]
I had the same thing in mind, but thought having separate mutation would be better.

**Comment by Aadeesh11** [comment]
You may close this pr if the change doesnt seem necessary.

**Comment by aadibajpai** [comment]
> I had the same thing in mind, but thought having separate mutation would be better.

I think it's smart to not add redundant code when you can just reuse the mutation for it

**Comment by Aadeesh11** [comment]
Sure thanks.

**Pull request closed without merging**
